services:
  bitwarden:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
    volumes:
      - "${DATA_PATH}:/data"
    image: vaultwarden/server:latest
    labels:  
      createdBy: "Apps"
    environment:
      SIGNUPS_ALLOWED: 'true'
      INVITATIONS_ALLOWED: 'true'
      WEBSOCKET_ENABLED: 'false'
      ADMIN_TOKEN: '${ADMIN_TOKEN}'
networks:  
  1panel-network:  
    external: true
