services:
  reader:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8080"
    volumes:
      - "${DATA_PATH}/log:/log"
      - "${DATA_PATH}/storage:/storage"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - READER_APP_USERLIMIT=${USER_LIMIT}
      - READER_APP_USERBOOKLIMIT=${BOOK_LIMIT}
      - READER_APP_CACHECHAPTERCONTENT=true
      # 如果启用远程webview，需要取消注释下面的 remote-webview 服务
      # - READER_APP_REMOTEWEBVIEWAPI=http://remote-webview:8050 #开启远程webview
      - READER_APP_SECURE=true
      - READER_APP_SECUREKEY=${PASSWORD}
      - READER_APP_INVITECODE=${INVITE_CODE}
    image: hectorqin/reader:3.2.9
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
