services:
  audiobookshelf:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
    volumes:
      - "${DATA_PATH1}:/audiobooks"
      - "${DATA_PATH2}:/podcasts"
      - "${DATA_PATH}:/config"
      - "${DATA_PATH3}:/metadata"
    image: advplyr/audiobookshelf:latest
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
