services:
  linkding:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:9090"
    volumes:
      - "${DATA_PATH}:/etc/linkding/data"
    image: sissbruecker/linkding:latest
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
